In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Import CSV

In [ ]:
choco = pd.read_csv("/content/drive/MyDrive/Chocolate Sales.csv")
choco.head()

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,04-Jan-22,"$5,320",180
1,Van Tuxwell,India,85% Dark Bars,01-Aug-22,"$7,896",94
2,Gigi Bohling,India,Peanut Butter Cubes,07-Jul-22,"$4,501",91
3,Jan Morforth,Australia,Peanut Butter Cubes,27-Apr-22,"$12,726",342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24-Feb-22,"$13,685",184

In [ ]:
cek = choco['Product'].value_counts()
cek

Product
Eclairs                 60
50% Dark Bites          60
Smooth Sliky Salty      59
White Choc              58
Drinking Coco           56
Spicy Special Slims     54
Organic Choco Syrup     52
85% Dark Bars           50
Fruit & Nut Bars        50
After Nines             50
Peanut Butter Cubes     49
99% Dark & Pure         49
Milk Bars               49
Raspberry Choco         48
Almond Choco            48
Orange Choco            47
Mint Chip Choco         45
Manuka Honey Choco      45
Caramel Stuffed Bars    43
70% Dark Bites          42
Baker's Choco Chips     41
Choco Coated Almonds    39
Name: count, dtype: int64

In [ ]:
choco.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1094 entries, 0 to 1093
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   1094 non-null   object
 1   Country        1094 non-null   object
 2   Product        1094 non-null   object
 3   Date           1094 non-null   object
 4   Amount         1094 non-null   object
 5   Boxes Shipped  1094 non-null   int64
dtypes: int64(1), object(5)
memory usage: 51.4+ KB

## Cleaning Data

In [ ]:
# Ubah ke dalam Float karena kolom masih string
choco['Amount'] = choco['Amount'].replace('[\$,]', '', regex=True)
choco['Amount'] = choco['Amount'].astype(float)

# Ubah ke format datetime
choco['Date'] = pd.to_datetime(choco["Date"])

# Simpan ke dalam variabel baru
choco_clean = choco
choco_clean.head()

<>:2: SyntaxWarning: invalid escape sequence '\$'
<>:2: SyntaxWarning: invalid escape sequence '\$'
/tmp/ipython-input-304/1625536710.py:2: SyntaxWarning: invalid escape sequence '\$'
  choco['Amount'] = choco['Amount'].replace('[\$,]', '', regex=True)
/tmp/ipython-input-304/1625536710.py:6: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  choco['Date'] = pd.to_datetime(choco["Date"])

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,2022-01-04,5320.0,180
1,Van Tuxwell,India,85% Dark Bars,2022-08-01,7896.0,94
2,Gigi Bohling,India,Peanut Butter Cubes,2022-07-07,4501.0,91
3,Jan Morforth,Australia,Peanut Butter Cubes,2022-04-27,12726.0,342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,2022-02-24,13685.0,184

In [ ]:
choco_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1094 entries, 0 to 1093
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   1094 non-null   object
 1   Country        1094 non-null   object
 2   Product        1094 non-null   object
 3   Date           1094 non-null   datetime64[ns]
 4   Amount         1094 non-null   float64
 5   Boxes Shipped  1094 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(1), object(3)
memory usage: 51.4+ KB

In [ ]:
# Simpan ke dalam Excel
sales_chocolates = choco_clean.to_excel('sales_chocolates.xlsx', index=False)
print(sales_chocolates)

None

In [ ]:
choco_clean['Product'].value_counts()

Product
Eclairs                 60
50% Dark Bites          60
Smooth Sliky Salty      59
White Choc              58
Drinking Coco           56
Spicy Special Slims     54
Organic Choco Syrup     52
85% Dark Bars           50
Fruit & Nut Bars        50
After Nines             50
Peanut Butter Cubes     49
99% Dark & Pure         49
Milk Bars               49
Raspberry Choco         48
Almond Choco            48
Orange Choco            47
Mint Chip Choco         45
Manuka Honey Choco      45
Caramel Stuffed Bars    43
70% Dark Bites          42
Baker's Choco Chips     41
Choco Coated Almonds    39
Name: count, dtype: int64

In [ ]:
product_sales = choco_clean.groupby('Product')['Amount'].sum().reset_index()
product_sales = product_sales.sort_values(by='Amount', ascending=False)
display(product_sales)

                 Product    Amount
19    Smooth Sliky Salty  349692.0
0         50% Dark Bites  341712.0
21            White Choc  329147.0
17   Peanut Butter Cubes  324842.0
10               Eclairs  312445.0
3        99% Dark & Pure  299796.0
2          85% Dark Bars  299229.0
16   Organic Choco Syrup  294700.0
20   Spicy Special Slims  293454.0
14       Mint Chip Choco  283969.0
5           Almond Choco  277536.0
12    Manuka Honey Choco  275541.0
13             Milk Bars  269248.0
18       Raspberry Choco  264740.0
4            After Nines  261331.0
11      Fruit & Nut Bars  259147.0
9          Drinking Coco  256655.0
15          Orange Choco  256144.0
6    Baker's Choco Chips  249613.0
8   Choco Coated Almonds  241486.0
7   Caramel Stuffed Bars  231588.0
1         70% Dark Bites  211610.0